name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        PACKAGES_READER_GITHUB_TOKEN: ${{ secrets.PACKAGES_READER_GITHUB_TOKEN }}
        PACKAGES_READER_GITHUB_USER: ${{ secrets.PACKAGES_READER_GITHUB_USER }}
        CWM_WORKER_OPERATOR_DEPLOY_KEY: ${{ secrets.CWM_WORKER_OPERATOR_DEPLOY_KEY }}
      run: |
        sudo bin/install_minikube.sh && minikube version &&\
        bin/minikube_start.sh &&\
        sudo bin/install_kubectl.sh && kubectl version --client &&\
        sudo bin/install_helm.sh && helm version &&\
        sudo bin/install_python.sh &&\
        bin/python_init_venv_requirements_module.sh &&\
        bin/minikube_wait.sh &&\
        bin/prometheus_deploy_wait.sh &&\
        . venv/bin/activate &&\
        pytest &&\
        echo "${CWM_WORKER_OPERATOR_DEPLOY_KEY}" > cwm_worker_operator_deploy_key &&\
        chmod 400 cwm_worker_operator_deploy_key &&\
        export GIT_SSH_COMMAND="ssh -i $(pwd)/cwm_worker_operator_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
        git clone git@github.com:CloudWebManage/cwm-worker-operator.git &&\
        git config --global user.name "cwm-worker-deployment CI" &&\
        git config --global user.email "cwm-worker-deployment-ci@localhost" &&\
        cd cwm-worker-operator &&\
        cat ../requirements.txt > requirements-cwm-worker-deployment.txt &&\
        echo "-e \"git+https://github.com/CloudWebManage/cwm-worker-deployment.git@${GITHUB_SHA}#egg=cwm-worker-deployment\"" >> requirements-cwm-worker-deployment.txt &&\
        git add requirements-cwm-worker-deployment.txt &&\
        git commit -m "automatic update of cwm-worker-deployment" &&\
        git push origin master
